---
apiVersion: v1
kind: Node
metadata:
  labels:
    node-role.kubernetes.io/ht: ""
  name: worker-0
---
apiVersion: v1
kind: Node
metadata:
  labels:
    node-role.kubernetes.io/standard: ""
  name: worker-1
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: ht
  namespace: openshift-machine-config-operator
  labels:
    machineconfiguration.openshift.io/role: ht
    pools.operator.machineconfiguration.openshift.io/ht: ""
spec:
  paused: false
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values: [worker,ht]
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/ht: ""
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: standard
  namespace: openshift-machine-config-operator
  labels:
    machineconfiguration.openshift.io/role: standard
    pools.operator.machineconfiguration.openshift.io/standard: ""
spec:
  paused: false
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values: [worker,standard]
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/standard: ""

