---
apiVersion: v1
kind: Namespace
metadata:
  name: tm-test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guaranteed-pods
  labels:
    app: guaranteed-pods
  namespace: tm-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guaranteed-pods
  template:
    metadata:
      labels:
        app: guaranteed-pods
    spec:
      containers:
        - name: tm-1
          image: registry.access.redhat.com/ubi8/ubi:8.1
          command: ["/bin/bash", "-c", "sleep 1d"]
          resources:
            requests:
              memory: "200Mi"
              cpu: 2
            limits:
              memory: "200Mi"
              cpu: 2
        - name: tm-2
          image: registry.access.redhat.com/ubi8/ubi:8.1
          command: ["/bin/bash", "-c", "sleep 10h"]
          resources:
            requests:
              memory: "250Mi"
              cpu: 3
            limits:
              memory: "250Mi"
              cpu: 3