---
apiVersion: v1
kind: Node
metadata:
  labels:
    node-role.kubernetes.io/ht: ""
  name: worker-0
---
apiVersion: v1
kind: Node
metadata:
  labels:
    node-role.kubernetes.io/standard: ""
  name: worker-1

